server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smosp
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    user:
      name: disabled
      password: disabled

  mail:
    host: smtp.gmail.com
    port: 587
    username: sep490gr47@gmail.com
    password: mwnp jbqa uwfd angv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: "eW91ci0yNTYtYml0LXNlY3JldC1rZXktY2hhbmdlLXRoaXMtaW4tcHJvZHVjdGlvbi1tdXN0LWJlLWxvbmctZW5vdWdo"
  expiration: 86400000
  refresh-expiration: 604800000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.sep490_g47.smosp: DEBUG
    org.springframework.security: DEBUG

app:
  base-url: http://localhost:8080